name: Deploy to Azure Storage and Purge CDN
on: [push]

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
      
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show  
          # You can write your Azure CLI inline scripts here.
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: checkout repository
        uses: actions/checkout@v3

      # Step 2: Azure CLI Login
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Upload files to Azure Storage $web folder
      - name: Upload to Azure Storage
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch \
            --account-name sacrcjen \
            --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
            --source './devcard-bs5/' \
            --destination '$web' \
            --pattern '*.html'
            --overwrite                      
