name: Deploy to Azure Storage and Purge CDN

on:
  push:
    branches:
      - main  # Deploy on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the GitHub repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Login to Azure using a service principal
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Define this secret in your GitHub repository settings

    # Step 3: Upload files to Azure Storage $web folder
    - name: Upload to Azure Storage
      run: |
        az storage blob upload-batch \
          --account-name <your-storage-account-name> \
          --source ./your-local-directory \
          --destination '$web' \
          --overwrite

    # Step 4: Purge Azure CDN endpoint
    - name: Purge Azure CDN Endpoint
      run: |
        az cdn endpoint purge \
          --resource-group <your-resource-group> \
          --profile-name <your-cdn-profile-name> \
          --name <your-cdn-endpoint-name> \
          --content-paths '/*'
